import fs from 'node:fs';
import path from 'node:path';
import {
  SlashCommandBuilder, PermissionFlagsBits, ChannelType, EmbedBuilder,
  ActionRowBuilder, ButtonBuilder, ButtonStyle, AttachmentBuilder
} from 'discord.js';

const dataFile=path.resolve('data/features.json');
const read=()=>{try{return JSON.parse(fs.readFileSync(dataFile,'utf8'));}catch{return {warnings:{},polls:{}};}};
const write=d=>{fs.mkdirSync(path.dirname(dataFile),{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(d,null,2));};
const role=(g,n)=>g.roles.cache.find(r=>r.name===n);
const channel=(g,n)=>g.channels.cache.find(c=>c.name===n||c.name.endsWith(`・${n}`));
const staffRoles=['CEO','Co-CEO','COO','CTO','CMO','Chief of Staff','Board of Directors','Department Director','Team Lead','Human Resources','Support'];
const isStaff=m=>m.permissions.has(PermissionFlagsBits.Administrator)||staffRoles.some(n=>m.roles.cache.has(role(m.guild,n)?.id));
const ephemeral={ephemeral:true};
const commands=[
 new SlashCommandBuilder().setName('verify').setDescription('Join the QDucks community'),
 new SlashCommandBuilder().setName('ticket').setDescription('Open a private QDucks ticket').addStringOption(o=>o.setName('type').setDescription('Ticket type').setRequired(true).addChoices({name:'Support',value:'support'},{name:'Staff application',value:'application'},{name:'Partnership',value:'partnership'},{name:'Report',value:'report'})).addStringOption(o=>o.setName('reason').setDescription('What do you need help with?').setRequired(true)),
 new SlashCommandBuilder().setName('suggest').setDescription('Suggest something for QDucks').addStringOption(o=>o.setName('idea').setDescription('Your suggestion').setRequired(true)),
 new SlashCommandBuilder().setName('poll').setDescription('Create a community poll').addStringOption(o=>o.setName('question').setDescription('Poll question').setRequired(true)).addStringOption(o=>o.setName('options').setDescription('Options separated by | (2-5)').setRequired(true)),
 new SlashCommandBuilder().setName('announce').setDescription('Send a QDucks announcement').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Destination').setRequired(true).addChannelTypes(ChannelType.GuildText)).addStringOption(o=>o.setName('message').setDescription('Announcement text').setRequired(true)).addStringOption(o=>o.setName('ping').setDescription('Optional notification role').addChoices({name:'Announcements',value:'Announcements Ping'},{name:'Updates',value:'Updates Ping'},{name:'Events',value:'Events Ping'},{name:'Giveaways',value:'Giveaways Ping'})),
 new SlashCommandBuilder().setName('meeting').setDescription('Schedule a QDucks meeting').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('title').setDescription('Meeting title').setRequired(true)).addStringOption(o=>o.setName('time').setDescription('Date/time including timezone').setRequired(true)).addStringOption(o=>o.setName('team').setDescription('Who should attend?').setRequired(true)),
 new SlashCommandBuilder().setName('warn').setDescription('Warn a member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)),
 new SlashCommandBuilder().setName('mute').setDescription('Temporarily mute a member').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('1-40320 minutes').setRequired(true).setMinValue(1).setMaxValue(40320)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 new SlashCommandBuilder().setName('kick').setDescription('Kick a member').setDefaultMemberPermissions(PermissionFlagsBits.KickMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 new SlashCommandBuilder().setName('ban').setDescription('Ban a member').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),
 new SlashCommandBuilder().setName('rolepanel').setDescription('Post notification-role buttons').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
 new SlashCommandBuilder().setName('serverstatus').setDescription('Show QDucks server and bot status'),
 new SlashCommandBuilder().setName('help').setDescription('Show Quackity commands'),
 new SlashCommandBuilder().setName('warnings').setDescription('View a member’s warnings').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)),
 new SlashCommandBuilder().setName('clearwarns').setDescription('Clear a member’s warnings').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)),
 new SlashCommandBuilder().setName('staffnote').setDescription('Add a private note about a staff member').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addUserOption(o=>o.setName('member').setDescription('Staff member').setRequired(true)).addStringOption(o=>o.setName('note').setDescription('Private note').setRequired(true)),
 new SlashCommandBuilder().setName('ticketadd').setDescription('Add someone to this ticket').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)),
 new SlashCommandBuilder().setName('ticketremove').setDescription('Remove someone from this ticket').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)),
 new SlashCommandBuilder().setName('project').setDescription('Manage a QDucks project').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels).addSubcommand(s=>s.setName('create').setDescription('Create a project space').addStringOption(o=>o.setName('name').setDescription('Project name').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Description').setRequired(true))).addSubcommand(s=>s.setName('update').setDescription('Post a project update').addStringOption(o=>o.setName('name').setDescription('Project name').setRequired(true)).addStringOption(o=>o.setName('update').setDescription('Update').setRequired(true))).addSubcommand(s=>s.setName('complete').setDescription('Mark a project completed').addStringOption(o=>o.setName('name').setDescription('Project name').setRequired(true))),
 new SlashCommandBuilder().setName('event').setDescription('Create a QDucks event signup').setDefaultMemberPermissions(PermissionFlagsBits.ManageEvents).addStringOption(o=>o.setName('title').setDescription('Event title').setRequired(true)).addStringOption(o=>o.setName('time').setDescription('Date/time and timezone').setRequired(true)).addStringOption(o=>o.setName('description').setDescription('Details').setRequired(true)),
 new SlashCommandBuilder().setName('giveaway').setDescription('Start a timed giveaway').setDefaultMemberPermissions(PermissionFlagsBits.ManageEvents).addStringOption(o=>o.setName('prize').setDescription('Prize').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Duration in minutes').setRequired(true).setMinValue(1).setMaxValue(10080)).addIntegerOption(o=>o.setName('winners').setDescription('Number of winners').setRequired(true).setMinValue(1).setMaxValue(10))
];
export const featureCommands=commands;

const rows=(guildId=null)=>[
 new ActionRowBuilder().addComponents(
  new ButtonBuilder().setCustomId(`role:${guildId?guildId+':':''}Announcements Ping`).setLabel('Announcements').setEmoji('📢').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`role:${guildId?guildId+':':''}Updates Ping`).setLabel('Updates').setEmoji('🚀').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`role:${guildId?guildId+':':''}Events Ping`).setLabel('Events').setEmoji('🎉').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`role:${guildId?guildId+':':''}Giveaways Ping`).setLabel('Giveaways').setEmoji('🎁').setStyle(ButtonStyle.Primary))];

export function installFeatures(client){
 client.on('guildMemberAdd',async m=>{try{const c=channel(m.guild,'welcome');if(c?.isTextBased())await c.send(`🦆 Welcome to **QDucks**, ${m}! Check your DMs to complete onboarding.`);await m.send({embeds:[new EmbedBuilder().setColor(0xFEE75C).setTitle('🦆 Welcome to QDucks!').setDescription('Welcome to the complete QDucks community. Please accept the community rules to verify. QDucks account linking will be added later inside the official QDucks system.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`onboard:${m.guild.id}`).setLabel('Accept rules & join').setEmoji('✅').setStyle(ButtonStyle.Success))]});}catch(e){const c=channel(m.guild,'welcome');if(c?.isTextBased())await c.send(`${m}, I could not DM you. Please enable DMs from server members and rejoin or contact Support.`).catch(()=>{});}});
 client.on('guildMemberRemove',async m=>{const c=channel(m.guild,'join-leave-logs');if(c?.isTextBased())await c.send(`👋 **${m.user.tag}** left QDucks.`).catch(()=>{});});
 client.on('messageDelete',async m=>{if(!m.guild||m.author?.bot)return;const c=channel(m.guild,'moderation-logs');if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setColor(0xED4245).setTitle('🗑️ Message deleted').setDescription((m.content||'*Content unavailable*').slice(0,4000)).addFields({name:'Member',value:`${m.author}`},{name:'Channel',value:`${m.channel}`}).setTimestamp()]}).catch(()=>{});});
 client.on('messageUpdate',async(a,b)=>{if(!b.guild||b.author?.bot||a.content===b.content)return;const c=channel(b.guild,'moderation-logs');if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setColor(0xFEE75C).setTitle('✏️ Message edited').addFields({name:'Before',value:(a.content||'*Unavailable*').slice(0,1000)},{name:'After',value:(b.content||'*Unavailable*').slice(0,1000)},{name:'Channel',value:`${b.channel}`}).setTimestamp()]}).catch(()=>{});});
 client.on('interactionCreate',async i=>{
  if(i.isButton()){
   if(i.customId.startsWith('onboard:')){const guild=client.guilds.cache.get(i.customId.split(':')[1]),m=await guild?.members.fetch(i.user.id).catch(()=>null);if(!m)return i.reply({content:'I could not find your QDucks membership.',...ephemeral});for(const n of ['QDucks Community','Verified']){const r=role(guild,n);if(r)await m.roles.add(r,'Accepted QDucks rules in DM');}return i.update({embeds:[new EmbedBuilder().setColor(0x57F287).setTitle('✅ Welcome to QDucks!').setDescription('You are verified. Choose optional notifications below. QDucks account connection will be added later.')],components:rows(guild.id)});}
   if(i.customId.startsWith('role:')){const parts=i.customId.split(':'),guild=parts.length===3?client.guilds.cache.get(parts[1]):i.guild,n=parts.at(-1),m=i.guild?i.member:await guild?.members.fetch(i.user.id).catch(()=>null),r=guild&&role(guild,n);if(!r||!m)return i.reply({content:`Role ${n} is missing or you are no longer in QDucks.`,...ephemeral});const has=m.roles.cache.has(r.id);await m.roles[has?'remove':'add'](r);return i.reply({content:`${has?'Removed':'Added'} **${n}**.`,...ephemeral});}
   if(i.customId==='ticket:claim'){if(!isStaff(i.member))return i.reply({content:'Only QDucks staff can claim tickets.',...ephemeral});await i.channel.setTopic(`${i.channel.topic||''};claimed=${i.user.id}`);return i.reply(`🙋 Ticket claimed by ${i.user}.`);}
   if(i.customId==='ticket:close'){const owner=i.channel.topic?.match(/owner=(\d+)/)?.[1];if(!isStaff(i.member)&&owner!==i.user.id)return i.reply({content:'Only the ticket owner or staff can close this.',...ephemeral});const messages=await i.channel.messages.fetch({limit:100});const transcript=[...messages.values()].reverse().map(m=>`[${m.createdAt.toISOString()}] ${m.author.tag}: ${m.cleanContent}`).join('\n');const logs=channel(i.guild,'server-logs')||channel(i.guild,'moderation-logs');if(logs?.isTextBased())await logs.send({content:`🔒 Transcript for ${i.channel.name}`,files:[new AttachmentBuilder(Buffer.from(transcript||'No messages'),{name:`${i.channel.name}-transcript.txt`})]});await i.channel.permissionOverwrites.edit(owner,{SendMessages:false,ViewChannel:true});await i.channel.setName(`closed-${i.channel.name}`.slice(0,100));return i.update({content:'🔒 Ticket closed. Staff can reopen or delete it.',components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:reopen').setLabel('Reopen').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('ticket:delete').setLabel('Delete').setStyle(ButtonStyle.Danger))]});}
   if(i.customId==='ticket:reopen'){if(!isStaff(i.member))return i.reply({content:'Staff only.',...ephemeral});const owner=i.channel.topic?.match(/owner=(\d+)/)?.[1];if(owner)await i.channel.permissionOverwrites.edit(owner,{SendMessages:true,ViewChannel:true});await i.channel.setName(i.channel.name.replace(/^closed-/,''));return i.update({content:'🔓 Ticket reopened.',components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:claim').setLabel('Claim').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:close').setLabel('Close').setStyle(ButtonStyle.Danger))]});}
   if(i.customId==='ticket:delete'){if(!isStaff(i.member))return i.reply({content:'Staff only.',...ephemeral});await i.reply({content:'Deleting ticket…',...ephemeral});return i.channel.delete('Closed ticket deleted');}
   if(i.customId.startsWith('event:join:')){const d=read();d.events||={};d.events[i.customId]||=[];const list=d.events[i.customId],at=list.indexOf(i.user.id);at>=0?list.splice(at,1):list.push(i.user.id);write(d);return i.reply({content:`${at>=0?'Removed from':'Joined'} the event. Current signups: ${list.length}`,...ephemeral});}
   if(i.customId.startsWith('giveaway:join:')){const d=read();d.giveaways||={};d.giveaways[i.customId]||=[];const list=d.giveaways[i.customId];if(!list.includes(i.user.id))list.push(i.user.id);write(d);return i.reply({content:'🎁 You entered the giveaway!',...ephemeral});}
  }
  if(!i.isChatInputCommand()||!commands.some(c=>c.name===i.commandName))return;
  const g=i.guild;
  if(i.commandName==='verify'){for(const n of ['QDucks Community','Verified']){const r=role(g,n);if(r)await i.member.roles.add(r);}return i.reply({content:'✅ You are verified—welcome to QDucks!',...ephemeral});}
  if(i.commandName==='ticket'){const type=i.options.getString('type'),reason=i.options.getString('reason'),cat=channel(g,'🛟 HELP & SUPPORT');const ch=await g.channels.create({name:`🎫・${type}-${i.user.username}`.slice(0,100),topic:`owner=${i.user.id};type=${type}`,type:ChannelType.GuildText,parent:cat?.id,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},...staffRoles.flatMap(n=>role(g,n)?[{id:role(g,n).id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]}]:[])]});await ch.send({content:`${i.user} Staff will help you here.`,embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle(`🎫 ${type}`).setDescription(reason)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:claim').setLabel('Claim').setEmoji('🙋').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:close').setLabel('Close').setEmoji('🔒').setStyle(ButtonStyle.Danger))]});return i.reply({content:`✅ Ticket created: ${ch}`,...ephemeral});}
  if(i.commandName==='suggest'){const c=channel(g,'suggestions')||i.channel;const msg=await c.send({embeds:[new EmbedBuilder().setColor(0x57F287).setTitle('💡 QDucks Suggestion').setDescription(i.options.getString('idea')).setFooter({text:`Suggested by ${i.user.tag}`}).setTimestamp()]});await msg.react('👍');await msg.react('👎');return i.reply({content:`✅ Suggestion posted in ${c}.`,...ephemeral});}
  if(i.commandName==='poll'){const opts=i.options.getString('options').split('|').map(x=>x.trim()).filter(Boolean).slice(0,5);if(opts.length<2)return i.reply({content:'Use at least 2 options separated by |',...ephemeral});const nums=['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣'];const msg=await i.channel.send({embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle(`📊 ${i.options.getString('question')}`).setDescription(opts.map((x,j)=>`${nums[j]} ${x}`).join('\n')).setFooter({text:`Poll by ${i.user.tag}`})]});for(let j=0;j<opts.length;j++)await msg.react(nums[j]);return i.reply({content:'✅ Poll created.',...ephemeral});}
  if(i.commandName==='announce'){const c=i.options.getChannel('channel'),message=i.options.getString('message'),ping=i.options.getString('ping'),r=ping&&role(g,ping);await c.send({content:r?`${r}`:undefined,embeds:[new EmbedBuilder().setColor(0xF1C40F).setTitle('📢 QDucks Announcement').setDescription(message).setFooter({text:`Posted by ${i.user.tag}`}).setTimestamp()],allowedMentions:{roles:r?[r.id]:[]}});return i.reply({content:`✅ Announcement sent to ${c}.`,...ephemeral});}
  if(i.commandName==='meeting'){const c=channel(g,'meeting-announcements')||i.channel;await c.send({embeds:[new EmbedBuilder().setColor(0x9B59B6).setTitle(`📅 ${i.options.getString('title')}`).addFields({name:'When',value:i.options.getString('time')},{name:'Attending',value:i.options.getString('team')},{name:'Scheduled by',value:`${i.user}`}).setTimestamp()]});return i.reply({content:`✅ Meeting posted in ${c}.`,...ephemeral});}
  if(['warn','mute','kick','ban'].includes(i.commandName)){const u=i.options.getUser('member'),m=await g.members.fetch(u.id).catch(()=>null),reason=i.options.getString('reason')||'No reason provided';if(!m)return i.reply({content:'Member not found.',...ephemeral});if(i.commandName==='warn'){const d=read();d.warnings[u.id]||=[];d.warnings[u.id].push({reason,by:i.user.id,at:new Date().toISOString()});write(d);await u.send(`⚠️ You were warned in QDucks: ${reason}`).catch(()=>{});}if(i.commandName==='mute')await m.timeout(i.options.getInteger('minutes')*60000,reason);if(i.commandName==='kick')await m.kick(reason);if(i.commandName==='ban')await m.ban({reason});const log=channel(g,'moderation-logs');if(log?.isTextBased())await log.send(`🛡️ **${i.commandName.toUpperCase()}** • ${u.tag} • ${reason} • by ${i.user}`);return i.reply({content:`✅ ${i.commandName} completed for ${u.tag}.`,...ephemeral});}
  if(i.commandName==='rolepanel'){await i.channel.send({embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle('🦆 QDucks Notifications').setDescription('Choose what you want QDucks to notify you about. Tap again to remove a role.')],components:rows()});return i.reply({content:'✅ Role panel posted.',...ephemeral});}
  if(i.commandName==='serverstatus')return i.reply({embeds:[new EmbedBuilder().setColor(0x57F287).setTitle('🦆 QDucks Status').addFields({name:'Quackity',value:'✅ Online',inline:true},{name:'Community',value:`👥 ${g.memberCount} members`,inline:true},{name:'Server',value:'✅ Operational',inline:true}).setTimestamp()]});
  if(i.commandName==='warnings'){const u=i.options.getUser('member'),list=read().warnings[u.id]||[];return i.reply({content:list.length?list.map((w,j)=>`**#${j+1}** ${w.reason} — <@${w.by}> — ${w.at}`).join('\n').slice(0,1900):`${u.tag} has no warnings.`,...ephemeral});}
  if(i.commandName==='clearwarns'){const u=i.options.getUser('member'),d=read();d.warnings[u.id]=[];write(d);return i.reply({content:`✅ Cleared warnings for ${u.tag}.`,...ephemeral});}
  if(i.commandName==='staffnote'){const u=i.options.getUser('member'),d=read();d.staffNotes||={};d.staffNotes[u.id]||=[];d.staffNotes[u.id].push({note:i.options.getString('note'),by:i.user.id,at:new Date().toISOString()});write(d);const c=channel(g,'hr-records');if(c?.isTextBased())await c.send(`📝 Private staff note for ${u}: ${i.options.getString('note')} — by ${i.user}`);return i.reply({content:'✅ Private staff note saved.',...ephemeral});}
  if(['ticketadd','ticketremove'].includes(i.commandName)){if(!i.channel.topic?.includes('owner='))return i.reply({content:'Use this inside a Quackity ticket.',...ephemeral});const owner=i.channel.topic.match(/owner=(\d+)/)?.[1];if(!isStaff(i.member)&&owner!==i.user.id)return i.reply({content:'Only the ticket owner or staff can do this.',...ephemeral});const u=i.options.getUser('member'),add=i.commandName==='ticketadd';await i.channel.permissionOverwrites.edit(u.id,{ViewChannel:add,SendMessages:add,ReadMessageHistory:add});return i.reply(`${add?'Added':'Removed'} ${u}.`);}
  if(i.commandName==='project'){const sub=i.options.getSubcommand(),name=i.options.getString('name'),slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70);if(sub==='create'){const parent=await g.channels.create({name:`📁 PROJECT — ${name}`.slice(0,100),type:ChannelType.GuildCategory,permissionOverwrites:[{id:g.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},...['CEO','Co-CEO','COO','CTO','Department Director','Team Lead','Developer','Designer','Media Team'].flatMap(n=>role(g,n)?[{id:role(g,n).id,allow:[PermissionFlagsBits.ViewChannel]}]:[])]});for(const [icon,n] of [['💬','project-chat'],['📋','tasks'],['💻','development'],['🎨','assets'],['🧪','testing'],['📢','updates']])await g.channels.create({name:`${icon}・${slug}-${n}`.slice(0,100),type:ChannelType.GuildText,parent:parent.id});await channel(g,'project-announcements')?.send({embeds:[new EmbedBuilder().setColor(0x57F287).setTitle(`🚀 New QDucks project: ${name}`).setDescription(i.options.getString('description'))]});return i.reply({content:`✅ Project space created: **${name}**`,...ephemeral});}const c=channel(g,sub==='update'?'project-updates':'completed-projects')||i.channel;await c.send({embeds:[new EmbedBuilder().setColor(sub==='update'?0x5865F2:0x57F287).setTitle(`${sub==='update'?'📈 Project update':'✅ Project completed'}: ${name}`).setDescription(sub==='update'?i.options.getString('update'):'This QDucks project has been marked complete.').setFooter({text:`By ${i.user.tag}`}).setTimestamp()]});return i.reply({content:`✅ Project ${sub} posted.`,...ephemeral});}
  if(i.commandName==='event'){const c=channel(g,'event-announcements')||i.channel,id=`event:join:${Date.now()}`;await c.send({content:role(g,'Events Ping')?`${role(g,'Events Ping')}`:undefined,embeds:[new EmbedBuilder().setColor(0x9B59B6).setTitle(`🎉 ${i.options.getString('title')}`).setDescription(i.options.getString('description')).addFields({name:'When',value:i.options.getString('time')}).setFooter({text:'Tap below to join'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(id).setLabel('Join / Leave event').setEmoji('🎟️').setStyle(ButtonStyle.Success))],allowedMentions:{roles:role(g,'Events Ping')?[role(g,'Events Ping').id]:[]}});return i.reply({content:`✅ Event posted in ${c}.`,...ephemeral});}
  if(i.commandName==='giveaway'){const c=channel(g,'giveaways')||i.channel,prize=i.options.getString('prize'),minutes=i.options.getInteger('minutes'),count=i.options.getInteger('winners'),id=`giveaway:join:${Date.now()}`,d=read();d.giveaways||={};d.giveaways[id]=[];write(d);const msg=await c.send({content:role(g,'Giveaways Ping')?`${role(g,'Giveaways Ping')}`:undefined,embeds:[new EmbedBuilder().setColor(0xEB459E).setTitle(`🎁 ${prize}`).setDescription(`Ends in **${minutes} minute(s)**\nWinners: **${count}**`).setFooter({text:`Hosted by ${i.user.tag}`})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(id).setLabel('Enter giveaway').setEmoji('🎁').setStyle(ButtonStyle.Success))],allowedMentions:{roles:role(g,'Giveaways Ping')?[role(g,'Giveaways Ping').id]:[]}});setTimeout(async()=>{const data=read(),entries=data.giveaways?.[id]||[],winners=[...entries].sort(()=>Math.random()-.5).slice(0,count);await c.send(winners.length?`🎉 Congratulations ${winners.map(x=>`<@${x}>`).join(', ')}! You won **${prize}**.`:`No valid entries for **${prize}**.`);await msg.edit({components:[]}).catch(()=>{});},minutes*60000);return i.reply({content:`✅ Giveaway started in ${c}.`,...ephemeral});}
  if(i.commandName==='help')return i.reply({embeds:[new EmbedBuilder().setColor(0xFEE75C).setTitle('🦆 Quackity Help').setDescription('**Community**\n`/verify` `/ticket` `/ticketadd` `/ticketremove` `/suggest` `/poll` `/serverstatus`\n\n**Staff**\n`/announce` `/meeting` `/event` `/giveaway` `/project` `/warn` `/warnings` `/clearwarns` `/staffnote` `/mute` `/kick` `/ban` `/rolepanel` `/updserver`')] ,...ephemeral});
 });
}
